services:
  form-db:
    image: postgres:13
    container_name: form-db
    hostname: form-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: adm
      POSTGRES_DB: form
    networks:
      - form-creator

  form-redis:
    image: 'redis:alpine'
    container_name: form-redis
    ports:
      - '6379:6379'
    networks:
      - form-creator

  backend:
    build: ./back
    container_name: backend
    ports:
      - 5000:5000
    env_file:
      - ./back/.env
    depends_on:
      - form-db
      - form-redis
    networks:
      - form-creator

  frontend:
    build: ./front
    container_name: frontend
    ports:
      - 3000:3000
    env_file:
      - ./front/.env
    depends_on:
      - backend
    networks:
      - form-creator

networks:
  form-creator:
